In [1]:
import torch

In [105]:
# input-embedding:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [112]:
# GOAL: To have the context-vector z_2: 
# "z_2 is a rich representation of x_2(same shape) with information about other tokens incorporated into it."

# Find `attention_score_2`:
query = inputs[1]
attention_score_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attention_score_2[i] = torch.dot(query, x_i)

print('Attention-Score BEFORE Softmax:\n', attention_score_2)

# Normalize `attention_score_2` with softmax:
attention_score_2 = torch.softmax(attention_score_2, dim=0) # becomes "attention-weights"

print('\nAttention-Score AFTER Softmax:\n', attention_score_2)

# Finding z_2
context_z2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    context_z2 += x_i * attention_score_2[i]

context_z2 

Attention-Score BEFORE Softmax:
 tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

Attention-Score AFTER Softmax:
 tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])


tensor([0.4419, 0.6515, 0.5683])

# **Revising**

In [2]:
# input-embedding:
x = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

x_2 = x[1]
attn_score_2 = x * x_2
attn_score_2 = torch.sum(attn_score_2, dim=-1)
attn_score_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [3]:
attn_weight_2 = attn_score_2.softmax(dim=-1)
attn_weight_2

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [7]:
# torch.zeros()
context_vector2 = torch.zeros(x_2.shape)
for i, x_i in enumerate(x):
    context_vector2 += (attn_weight_2[i] * x_i)
    # print(attn_weight_2[i] * x_i)
context_vector2

tensor([0.4419, 0.6515, 0.5683])

In [ ]:
context_z2_v2 = torch.zeros(x_2.shape)
for i, x_i in enumerate(x):
    context_z2_v2 += x_i * attn_weight_2[i]

tensor([0.1023, 0.0357, 0.2117])
tensor([0.1308, 0.2070, 0.1570])
tensor([0.1356, 0.2022, 0.1523])
tensor([0.0523, 0.1380, 0.0785])
tensor([0.1832, 0.0595, 0.0238])
tensor([0.0119, 0.1903, 0.1308])


In [117]:

# for x2_i in attn_weight_2:
#     ...

## **From OLD:**

In [ ]:
query = inputs[1]
attention_score_2 = torch.empty(inputs.shape[0])
attention_score_2 # contains Random Values
                  # Each time running of the CELL will output different value

tensor([-2.4642e-35,  1.6549e-42,  2.3694e-38,  2.3694e-38,  3.6013e-43,
         6.3100e-01])

In [42]:
for i, x_i in enumerate(inputs):
    attention_score_2[i] = torch.dot(query, x_i)
attention_score_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [ ]:

# # Normalize `attention_score_2` with softmax:
# attention_score_2 = torch.softmax(attention_score_2, dim=0) # becomes "attention-weights"

# # Finding z_2
# context_z2 = torch.zeros(query.shape)
# for i, x_i in enumerate(inputs):
#     context_z2 += x_i * attention_score_2[i]

# context_z2 